apiVersion: v1
kind: Namespace
metadata:
  name: $APP-$APP_DEPLOY_ENV

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP-$APP_DEPLOY_ENV
  namespace: $APP-$APP_DEPLOY_ENV
  labels:
    app: $APP
spec:
  replicas: $POD_COUNT
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: $APP
  template:
    metadata:
      labels:
        app: $APP
    spec:
      containers:
      - name: $APP
        image: $ECR_REGISTRY/$APP:$GITHUB_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: $K8S_RESOURCES_LIMITS_CPU
            memory: $K8S_RESOURCES_LIMITS_MEMORY
          requests:
            cpu: $K8S_RESOURCES_REQUESTS_CPU
            memory: $K8S_RESOURCES_REQUESTS_MEMORY
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 60
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 3
        env:
        - name: FLASK_ENV
          value: $APP_DEPLOY_ENV
        - name: PYTHONUNBUFFERED
          value: "1"
---

apiVersion: v1
kind: Service
metadata:
  name: $APP-$APP_DEPLOY_ENV
  namespace: $APP-$APP_DEPLOY_ENV
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: $APP-$APP_DEPLOY_ENV$DOMAIN
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8000"
spec:
  selector:
    app: $APP
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: $SERVER_PORT

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: $APP-$APP_DEPLOY_ENV
  namespace: $APP-$APP_DEPLOY_ENV
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $APP-$APP_DEPLOY_ENV
  minReplicas: $K8S_HPA_MIN_REPLICAS
  maxReplicas: $K8S_HPA_MAX_REPLICAS
  targetCPUUtilizationPercentage: $K8S_HPA_CPU_UTILIZATION
