name: Publish to Docker
description: Build a container image and Pushes it to Docker registry
inputs:
  APP:
    required: true
    description: Name of the image to be built and pushed
  REGION:
    required: true
    description: AWS region where the image will be pushed
  AWS_ACCESS_KEY_ID:
    required: true
    description: AWS access key ID
  AWS_SECRET_ACCESS_KEY:
    required: true
    description: AWS secret access key

runs:
  using: composite
  steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      shell: bash
      run: |
        docker build -t $ECR_REGISTRY/${{ inputs.APP }}:${GITHUB_SHA} .
        docker push $ECR_REGISTRY/${{ inputs.APP }}:${GITHUB_SHA}

    - name: Log out of Amazon ECR
      shell: bash
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
