name: Build & Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    env:
      REGION: us-east-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Push the image
        uses: ./.github/actions
        with:
          REGION: ${{ env.REGION }}
          APP: ${{ github.repository }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SHARED_ACCOUNT_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SHARED_ACCOUNT_AWS_SECRET_ACCESS_KEY }}

  dev:
    needs: release
    name: Deploy to Dev
    environment:
      name: dev

    env:
      APP: ${{ github.repository }}
      REGION: us-east-1
      CLUSTER_NAME: dev-eks-cluster
      K8S_RESOURCES_REQUESTS_MEMORY: "2Gi"
      K8S_RESOURCES_REQUESTS_CPU: 1
      K8S_RESOURCES_LIMITS_MEMORY: "2Gi"
      K8S_RESOURCES_LIMITS_CPU: 1
      K8S_HPA_MIN_REPLICAS: 1
      K8S_HPA_MAX_REPLICAS: 1
      K8S_HPA_CPU_UTILIZATION: 80
      APP_DEPLOY_ENV: "dev"
      SERVER_PORT: "8000"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Deploy
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.REGION }}
          envsubst < eks/deployment.yml | kubectl apply -f -
 